export const de = {
    todo: 'ToDo',
    done: 'Erledigt',
    settings: 'Einstellungen',
    newTodo: 'Neues ToDo...',
    addTodo: 'ToDo hinzufügen',
    alert_name_length: 'Der ToDo-Name muss mindestens 3 Zeichen lang sein.',
    language: 'Sprache',
    name: 'Name',
    description: 'Bemerkung',
    copy: 'In die Zwischenablage kopieren',
    paste: 'Aus der Zwischenablage einfügen',
    priority: 'Priorität',
    low: 'Niedrig',
    medium: 'Mittel',
    high: 'Hoch',
    date: 'Datum',
    tomorrow: 'Morgen',
    today: 'Heute',
    yesterday: 'Gestern',
    january: 'Januar',
    february: 'Februar',
    march: 'März',
    april: 'April',
    mai: 'Mai',
    june: 'Juni',
    juli: 'Juli',
    august: 'August',
    september: 'September',
    october: 'Oktober',
    november: 'November',
    december: 'Dezember',
    design: 'Design',
    category: 'Kategorie',
    duration: 'Dauer',
    week: 'Woche',
    day: 'Tag',
    hour: 'Stunde',
    minute: 'Minute',
    weeks: 'Wochen',
    days: 'Tage',
    hours: 'Stunden',
    minutes: 'Minuten',
    alert_wrong_format: 'Das Format der Angaben für die Dauer konnte nicht gelesen werden',
    notification: 'Benachrichtigung',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    time: 'Uhrzeit',
    alert_notification_to_late: 'Der Zeitpunkt der Benachrichtigung kann nicht in der Vergangenheit liegen.',
    password: 'Passwort',
    signup: 'Registrieren',
    login: 'Anmelden',
    logout: 'Abmelden',
    account_creation_error: 'Es ist ein Fehler beim Erstellen des Accounts aufgetreten.',
    account_creation_success: 'Der Account wurde erfolgreich erstellt.',
    account_login_error: 'Es ist ein Fehler beim Anmelden aufgetreten.',
    account_login_success: 'Der Account wurde erfolgreich angemeldet.',
    account_logout_error: 'Es ist ein Fehler beim Abmelden aufgetreten.',
    account_logout_success: 'Der Account wurde erfolgreich abgemeldet.',
}

export const en = {
    todo: 'ToDo',
    done: 'Done',
    settings: 'Settings',
    newTodo: 'New ToDo...',
    addTodo: 'Add ToDo',
    alert_name_length: 'The ToDo name needs to be minimum 3 characters long.',
    language: 'Language',
    name: 'Name',
    description: 'Comment',
    copy: 'Copy to clipboard',
    paste: 'Paste from clipboard',
    priority: 'Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    date: 'Date',
    tomorrow: 'Tomorrow',
    today: 'Today',
    yesterday: 'Yesterday',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    mai: 'Mai',
    june: 'June',
    juli: 'Juli',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    design: 'Design',
    category: 'Category',
    duration: 'Duration',
    week: 'Week',
    day: 'Day',
    hour: 'Hour',
    minute: 'Minute',
    weeks: 'Weeks',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    alert_wrong_format: 'The format of the data for the duration could not be read',
    notification: 'Notification',
    cancel: 'Cancel',
    confirm: 'Confirm',
    time: 'Time',
    alert_notification_to_late: 'The time of the notification can not be in the past.',
    password: 'Password',
    signup: 'Sign up',
    login: 'Login',
    logout: 'Logout',
    account_creation_error: 'An error occurred while creating the account.',
    account_creation_success: 'The account was successfully created.',
    account_login_error: 'An error occurred while logging in.',
    account_login_success: 'The account was successfully logged in.',
    account_logout_error: 'An error occurred while logging out.',
    account_logout_success: 'The account was successfully logged out.',
}

export const fr = {
    todo: 'ToDo',
    done: 'Accomplis',
    settings: 'Paramètre',
    newTodo: 'Nouveau ToDo...',
    addTodo: 'Ajouter ToDo',
    alert_name_length: 'Le ToDo soit être au moins 3 caractères long.',
    language: 'Langue',
    name: 'Nom',
    description: 'Remarque',
    copy: 'Copier dans le presse-papier',
    paste: 'Coller depuis le presse-papier',
    priority: 'Priorité',
    low: 'Bas',
    medium: 'Milieu',
    high: 'Élevé',
    date: 'Date',
    tomorrow: 'Demain',
    today: "Aujourd'hui",
    yesterday: 'Hier',
    january: 'Janvier',
    february: 'Février',
    march: 'Mars',
    april: 'Avril',
    mai: 'Mai',
    june: 'Juin',
    juli: 'Juillet',
    august: 'Août',
    september: 'Septembre',
    october: 'October',
    november: 'Novembre',
    december: 'Décembre',
    design: 'Design',
    category: 'Catégorie',
    duration: 'Durée',
    week: 'Semaine',
    day: 'Jour',
    hour: 'Heure',
    minute: 'Minute',
    weeks: 'Semaines',
    days: 'Jours',
    hours: 'Heures',
    minutes: 'Minutes',
    alert_wrong_format: 'Le format des données pour la durée n\'a pas pu être lu',
    notification: 'Notification',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    time: 'Heure',
    alert_notification_to_late: 'Le moment de la notification ne peut pas être dans le passé.',
    password: 'Mot de passe',
    signup: 'S\'inscrire',
    login: 'Se connecter',
    logout: 'Se déconnecter',
    account_creation_error: 'Une erreur s\'est produite lors de la création du compte.',
    account_creation_success: 'Le compte a été créé avec succès.',
    account_login_error: 'Une erreur s\'est produite lors de la connexion.',
    account_login_success: 'Le compte a été connecté avec succès.',
    account_logout_error: 'Une erreur s\'est produite lors de la déconnexion.',
    account_logout_success: 'Le compte a été déconnecté avec succès.',
}


