import {TODO} from '@de'

export const de = {
    todo: TODO,
    done: 'Erledigt',
    settings: 'Einstellungen',
    newTodo: 'Neues ToDo...',
    addTodo: 'ToDo hinzufügen',
    alert: 'Der ToDo-Name muss mindestens 3 Zeichen lang sein.',
    language: 'Sprache',
    name: 'Name',
    description: 'Bemerkung',
    copy: 'In die Zwischenablage kopieren',
    paste: 'Aus der Zwischenablage einfügen',
    priority: 'Priorität',
    low: 'Niedrig',
    medium: 'Mittel',
    high: 'Hoch',
    date: 'Datum',
    tomorrow: 'Morgen',
    today: 'Heute',
    yesterday: 'Gestern',
    january: 'Januar',
    february: 'Februar',
    march: 'März',
    april: 'April',
    mai: 'Mai',
    june: 'Juni',
    juli: 'Juli',
    august: 'August',
    september: 'September',
    october: 'Oktober',
    november: 'November',
    december: 'Dezember',
    design: 'Design',
    category: 'Kategorie',
    duration: 'Dauer',
    week: 'Woche',
    day: 'Tag',
    hour: 'Stunde',
    minute: 'Minute',
    weeks: 'Wochen',
    days: 'Tage',
    hours: 'Stunden',
    minutes: 'Minuten',
}

export const en = {
    todo: 'ToDo',
    done: 'Done',
    settings: 'Settings',
    newTodo: 'New ToDo...',
    addTodo: 'Add ToDo',
    alert: 'The ToDo name needs to be minimum 3 characters long.',
    language: 'Language',
    name: 'Name',
    description: 'Comment',
    copy: 'Copy to clipboard',
    paste: 'Paste from clipboard',
    priority: 'Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    date: 'Date',
    tomorrow: 'Tomorrow',
    today: 'Today',
    yesterday: 'Yesterday',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    mai: 'Mai',
    june: 'June',
    juli: 'Juli',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    design: 'Design',
    category: 'Category',
    duration: 'Duration',
    week: 'Week',
    day: 'Day',
    hour: 'Hour',
    minute: 'Minute',
    weeks: 'Weeks',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
}

export const fr = {
    todo: 'ToDo',
    done: 'Accomplis',
    settings: 'Paramètre',
    newTodo: 'Nouveau ToDo...',
    addTodo: 'Ajouter ToDo',
    alert: 'Le ToDo soit être au moins 3 caractères long.',
    language: 'Langue',
    name: 'Nom',
    description: 'Remarque',
    copy: 'Copy to clipboard',
    paste: 'Paste from clipboard',
    priority: 'Priorité',
    low: 'Bas',
    medium: 'Milieu',
    high: 'Élevé',
    date: 'Date',
    tomorrow: 'Demain',
    today: "Aujourd'hui",
    yesterday: 'Hier',
    january: 'Janvier',
    february: 'Février',
    march: 'Mars',
    april: 'Avril',
    mai: 'Mai',
    june: 'Juin',
    juli: 'Juillet',
    august: 'Août',
    september: 'Septembre',
    october: 'October',
    november: 'Novembre',
    december: 'Décembre',
    design: 'Design',
    category: 'Catégorie',
    duration: 'Durée',
    week: 'Semaine',
    day: 'Jour',
    hour: 'Heure',
    minute: 'Minute',
    weeks: 'Semaines',
    days: 'Jours',
    hours: 'Heures',
    minutes: 'Minutes',
}


